apiVersion: v1
kind: Secret
metadata:
  name: acs-credentials
  namespace: acs-policy-sync
type: Opaque
stringData:
  central-url: "https://central-stackrox.apps.rosa.ky-public-02.9rmm.p3.openshiftapps.com"
  username: "admin"
  password: "MB60Nxf43E0jgfDRfX7b87NPf"
